version: '3.9'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: secret
    ports: ['5432:5432']
  redis:
    image: redis:7
    ports: ['6379:6379']
  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    command: start-dev --http-port 8081
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports: ['8081:8081']
  mailhog:
    image: mailhog/mailhog
    ports: ['8025:8025']
