# .github/workflows/weekly.yml - 优化版周报
name: Weekly Review

on:
  schedule:
    - cron: '0 0 * * 1'  # 每周一 UTC 00:00，北京时间 08:00
  workflow_dispatch:
    inputs:
      dry_run:
        description: '试运行（不发送通知）'
        required: false
        default: false
        type: boolean

jobs:
  weekly-review:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install --no-cache-dir -r requirements.txt

      - name: Run weekly summary
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DB_ID: ${{ secrets.NOTION_DB_ID }}
          DEEPSEEK_KEY: ${{ secrets.DEEPSEEK_KEY }}
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          LLM_PROVIDER: ${{ secrets.LLM_PROVIDER || 'deepseek' }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          EMAIL_SMTP_SERVER: ${{ secrets.EMAIL_SMTP_SERVER }}
          EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          TIMEZONE: ${{ secrets.TIMEZONE || 'Asia/Shanghai' }}
        run: |
          python -m src.main \
            --period weekly \
            ${{ github.event.inputs.dry_run == 'true' && '--dry-run' || '' }}
